#pragma once

using namespace std;

enum TokenType {
    PROGRAM,
    IDENTIFIER,
    
    LEFT_PAREN,RIGHT_PAREN,
    LEFT_BRACE,RIGHT_BRACE,
    COMMA,DOT,MINUS,PLUS,
    SEMICOLON,SLASH,STAR,ADDRESS,
    QUOTATION,MOD,

    STRING,BOOL,CHAR,INT,
    FLOAT,ARRAY,DOUBLE,CONSTANT,

    NOT,EQUAL,
    GREATER,LESS,
    TRUE,FALSE,

    AND,CLASS,ELSE,ELIF,
    FUNCTION,FOR,
    IF,NULL_EMPTY,OR,
    OUT,RETURN,WHILE,VOID,

    ERR,
    ParsingSuccess
};
